name: My Local Action

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Unity
      uses: actions/setup-unity@v1
      with:
        unityVersion: 2021.3.5f1
        components: Android
        unityEmail: ${{ secrets.UNITY_EMAIL }}
        unityPassword: ${{ secrets.UNITY_PASSWORD }}
        license: ${{ secrets.UNITY_LICENSE }}
        
    - name: Build Unity project
      run: |
        unity -quit -batchmode -projectPath . -executeMethod BuildScript.BuildAndroid
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: android-build
        path: ./Builds/Android # Change the path to your Android build directory
