name: Unity Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/unity-setup@v1
      with:
        unityVersion: 2021.3.5f1
        components: Android
        androidSdkPath: /usr/local/android-sdk

    - name: Cache Unity Builder
      uses: actions/cache@v2
      with:
        path: ~/.cache/unity-builder
        key: ${{ runner.os }}-unity-${{ hashFiles('**/*.csproj') }}

    - name: Build Android
      run: |
        unity-builder --buildTarget Android --outputPath Build
