name: Unity Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Unity
      run: |
        wget -q https://download.unity3d.com/download_unity/linux/unityhub_amd64.AppImage -O unityhub.AppImage
        chmod +x unityhub.AppImage
        ./unityhub.AppImage -- --install-location=/opt/Unity --components "Unity,Android Build Support"
        
    - name: Cache Unity Hub
      uses: actions/cache@v2
      with:
        path: /opt/Unity
        key: ${{ runner.os }}-unity-${{ hashFiles('**/*.csproj') }}

    - name: Build Android
      run: |
        /opt/Unity/Editor/Unity -quit -batchmode -nographics -projectPath . -executeMethod UnityEditor.Android.BuildPlayerWindow+BuildPlayerOptions.BuildPlayer -logFile /dev/stdout
